In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_excel("Ecommerce Dataset.xlsx")

In [5]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,831156,order_refunded,4/25/2018,COMSAN5AA13CA206621,1188.0,1,1188.00,100516225,Computing,Cfsd80620,...,Easypay,4/25/2018,Valid,"1,188",2018,4,2017-12,Apr-18,FY18,83736
1,864213,canceled,6/1/2018,MATHUA5AF70B5D6ADF3,36000.0,1,36000.00,100537896,Mobiles & Tablets,NaN,...,Easypay,6/1/2018,Gross,"36,000",2018,6,2018-5,Jun-18,FY18,110033
2,784089,canceled,3/15/2018,OTHPCB5A7D8A1240398,12000.0,2,24000.00,100479699,Others,NaN,...,Easypay,3/15/2018,Gross,"24,000",2018,3,2018-3,Mar-18,FY18,95206
3,465260,complete,5/7/2017,KureshiC_141-kemei,1599.0,1,1599.00,100301652,Beauty & Grooming,\N,...,cod,5/7/2017,Net,"1,599",2017,5,2017-5,May-17,FY17,43645
4,846044,received,5/11/2018,BAGVIT5AC4A6DD68342,310.0,3,3853.32,100526623,Beauty & Grooming,NaN,...,Payaxis,5/11/2018,Valid,930,2018,5,2017-10,May-18,FY18,64430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,680616,canceled,11/24/2017,MEFNAR59C8CA4424D12,298.0,1,2470.00,100417366,Men's Fashion,\N,...,Easypay,11/24/2017,Gross,298,2017,11,2017-2,Nov-17,FY18,33717
9996,325420,canceled,11/25/2016,Enviro_Enviro 3 In 1 Juicer ENJ-301,3675.0,1,3307.50,100223641,Appliances,\N,...,jazzvoucher,11/25/2016,Gross,"3,675",2016,11,2016-9,Nov-16,FY17,8543
9997,649516,complete,11/20/2017,MATIGE59BA6458A8F79-1,1889.0,1,2338.00,100398958,Mobiles & Tablets,\N,...,cod,11/20/2017,Net,"1,889",2017,11,2017-11,Nov-17,FY18,72481
9998,391461,canceled,1/21/2017,cr_MUZAFTI IRANI (500GM),185.0,1,335.00,100262643,Soghaat,\N,...,Payaxis,1/21/2017,Gross,185,2017,1,2016-12,Jan-17,FY17,28952
9999,447254,order_refunded,4/15/2017,Aladdin_3D_enlarge_Screen,290.0,1,290.00,100293787,Mobiles & Tablets,\N,...,cod,4/15/2017,Valid,290,2017,4,2016-7,Apr-17,FY17,688

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   item_id                10000 non-null  int64
 1   status                 10000 non-null  object
 2   created_at             10000 non-null  object
 3   sku                    10000 non-null  object
 4   price                  10000 non-null  float64
 5   qty_ordered            10000 non-null  int64
 6   grand_total            10000 non-null  float64
 7   increment_id           10000 non-null  object
 8   category_name_1        9997 non-null   object
 9   sales_commission_code  7699 non-null   object
 10  discount_amount        10000 non-null  float64
 11  payment_method         10000 non-null  object
 12  Working Date           10000 non-null  object
 13  BI Status              10000 non-null  object
 14   MV                    10000 non-null  object
 15  Year                   10000 non-null  int64
 16  Month                  10000 non-null  int64
 17  Customer Since         10000 non-null  object
 18  M-Y                    10000 non-null  object
 19  FY                     10000 non-null  object
 20  Customer ID            10000 non-null  int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.6+ MB

In [8]:
df.isnull().any

<bound method DataFrame.any of       item_id  status  created_at    sku  price  qty_ordered  grand_total  \
0       False   False       False  False  False        False        False
1       False   False       False  False  False        False        False
2       False   False       False  False  False        False        False
3       False   False       False  False  False        False        False
4       False   False       False  False  False        False        False
...       ...     ...         ...    ...    ...          ...          ...
9995    False   False       False  False  False        False        False
9996    False   False       False  False  False        False        False
9997    False   False       False  False  False        False        False
9998    False   False       False  False  False        False        False
9999    False   False       False  False  False        False        False

      increment_id  category_name_1  sales_commission_code  ...  \
0            False            False                  False  ...
1            False            False                   True  ...
2            False            False                   True  ...
3            False            False                  False  ...
4            False            False                   True  ...
...            ...              ...                    ...  ...
9995         False            False                  False  ...
9996         False            False                  False  ...
9997         False            False                  False  ...
9998         False            False                  False  ...
9999         False            False                  False  ...

      payment_method  Working Date  BI Status    MV    Year  Month  \
0              False         False      False  False  False  False
1              False         False      False  False  False  False
2              False         False      False  False  False  False
3              False         False      False  False  False  False
4              False         False      False  False  False  False
...              ...           ...        ...    ...    ...    ...
9995           False         False      False  False  False  False
9996           False         False      False  False  False  False
9997           False         False      False  False  False  False
9998           False         False      False  False  False  False
9999           False         False      False  False  False  False

      Customer Since    M-Y     FY  Customer ID
0              False  False  False        False
1              False  False  False        False
2              False  False  False        False
3              False  False  False        False
4              False  False  False        False
...              ...    ...    ...          ...
9995           False  False  False        False
9996           False  False  False        False
9997           False  False  False        False
9998           False  False  False        False
9999           False  False  False        False

[10000 rows x 21 columns]>

In [9]:
df.isnull()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,831156,order_refunded,4/25/2018,COMSAN5AA13CA206621,1188.0,1,1188.00,100516225,Computing,Cfsd80620,...,Easypay,4/25/2018,Valid,"1,188",2018,4,2017-12,Apr-18,FY18,83736
1,864213,canceled,6/1/2018,MATHUA5AF70B5D6ADF3,36000.0,1,36000.00,100537896,Mobiles & Tablets,NaN,...,Easypay,6/1/2018,Gross,"36,000",2018,6,2018-5,Jun-18,FY18,110033
2,784089,canceled,3/15/2018,OTHPCB5A7D8A1240398,12000.0,2,24000.00,100479699,Others,NaN,...,Easypay,3/15/2018,Gross,"24,000",2018,3,2018-3,Mar-18,FY18,95206
3,465260,complete,5/7/2017,KureshiC_141-kemei,1599.0,1,1599.00,100301652,Beauty & Grooming,\N,...,cod,5/7/2017,Net,"1,599",2017,5,2017-5,May-17,FY17,43645
4,846044,received,5/11/2018,BAGVIT5AC4A6DD68342,310.0,3,3853.32,100526623,Beauty & Grooming,NaN,...,Payaxis,5/11/2018,Valid,930,2018,5,2017-10,May-18,FY18,64430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,680616,canceled,11/24/2017,MEFNAR59C8CA4424D12,298.0,1,2470.00,100417366,Men's Fashion,\N,...,Easypay,11/24/2017,Gross,298,2017,11,2017-2,Nov-17,FY18,33717
9996,325420,canceled,11/25/2016,Enviro_Enviro 3 In 1 Juicer ENJ-301,3675.0,1,3307.50,100223641,Appliances,\N,...,jazzvoucher,11/25/2016,Gross,"3,675",2016,11,2016-9,Nov-16,FY17,8543
9997,649516,complete,11/20/2017,MATIGE59BA6458A8F79-1,1889.0,1,2338.00,100398958,Mobiles & Tablets,\N,...,cod,11/20/2017,Net,"1,889",2017,11,2017-11,Nov-17,FY18,72481
9998,391461,canceled,1/21/2017,cr_MUZAFTI IRANI (500GM),185.0,1,335.00,100262643,Soghaat,\N,...,Payaxis,1/21/2017,Gross,185,2017,1,2016-12,Jan-17,FY17,28952
9999,447254,order_refunded,4/15/2017,Aladdin_3D_enlarge_Screen,290.0,1,290.00,100293787,Mobiles & Tablets,\N,...,cod,4/15/2017,Valid,290,2017,4,2016-7,Apr-17,FY17,688

In [11]:
df["Month"].sum

<bound method Series.sum of 0        4
1        6
2        3
3        5
4        5
        ..
9995    11
9996    11
9997    11
9998     1
9999     4
Name: Month, Length: 10000, dtype: int64>

In [12]:
df["Month"].count

<bound method Series.count of 0        4
1        6
2        3
3        5
4        5
        ..
9995    11
9996    11
9997    11
9998     1
9999     4
Name: Month, Length: 10000, dtype: int64>

In [13]:
df["status"].count

<bound method Series.count of 0       order_refunded
1             canceled
2             canceled
3             complete
4             received
             ...
9995          canceled
9996          canceled
9997          complete
9998          canceled
9999    order_refunded
Name: status, Length: 10000, dtype: object>

In [15]:
df.head(10)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,831156,order_refunded,4/25/2018,COMSAN5AA13CA206621,1188.0,1,1188.00,100516225,Computing,Cfsd80620,...,Easypay,4/25/2018,Valid,"1,188",2018,4,2017-12,Apr-18,FY18,83736
1,864213,canceled,6/1/2018,MATHUA5AF70B5D6ADF3,36000.0,1,36000.00,100537896,Mobiles & Tablets,NaN,...,Easypay,6/1/2018,Gross,"36,000",2018,6,2018-5,Jun-18,FY18,110033
2,784089,canceled,3/15/2018,OTHPCB5A7D8A1240398,12000.0,2,24000.00,100479699,Others,NaN,...,Easypay,3/15/2018,Gross,"24,000",2018,3,2018-3,Mar-18,FY18,95206
3,465260,complete,5/7/2017,KureshiC_141-kemei,1599.0,1,1599.00,100301652,Beauty & Grooming,\N,...,cod,5/7/2017,Net,"1,599",2017,5,2017-5,May-17,FY17,43645
4,846044,received,5/11/2018,BAGVIT5AC4A6DD68342,310.0,3,3853.32,100526623,Beauty & Grooming,NaN,...,Payaxis,5/11/2018,Valid,930,2018,5,2017-10,May-18,FY18,64430
5,869322,received,6/9/2018,WOFTOO5AA849648ADE4,999.0,1,0.00,100540768,Women's Fashion,NaN,...,customercredit,6/9/2018,Valid,999,2018,6,2018-6,Jun-18,FY18,110680
6,396847,canceled,2/1/2017,infinix_Zero 4-Grey,22999.0,1,23199.00,100265592,Mobiles & Tablets,\N,...,Payaxis,2/1/2017,Gross,"22,999",2017,2,2016-9,Feb-17,FY17,8963
7,430606,canceled,3/24/2017,streets_SS-06-L,1000.0,1,2220.00,100284546,Men's Fashion,\N,...,Easypay,3/24/2017,Gross,"1,000",2017,3,2017-3,Mar-17,FY17,39042
8,510420,complete,6/11/2017,vitamin_Wipes,1275.0,1,2235.80,100324536,Health & Sports,\N,...,Easypay,6/11/2017,Net,"1,275",2017,6,2016-9,Jun-17,FY17,9541
9,821531,complete,4/8/2018,MEFBUY5A6B122D07266-40,699.0,1,1749.00,100510942,Men's Fashion,NaN,...,cod,4/8/2018,Net,699,2018,4,2018-4,Apr-18,FY18,103850

In [16]:
df.columns

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1',
       'sales_commission_code', 'discount_amount', 'payment_method',
       'Working Date', 'BI Status', ' MV ', 'Year', 'Month', 'Customer Since',
       'M-Y', 'FY', 'Customer ID'],
      dtype='object')

In [17]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,831156,order_refunded,4/25/2018,COMSAN5AA13CA206621,1188.0,1,1188.00,100516225,Computing,Cfsd80620,...,Easypay,4/25/2018,Valid,"1,188",2018,4,2017-12,Apr-18,FY18,83736
1,864213,canceled,6/1/2018,MATHUA5AF70B5D6ADF3,36000.0,1,36000.00,100537896,Mobiles & Tablets,NaN,...,Easypay,6/1/2018,Gross,"36,000",2018,6,2018-5,Jun-18,FY18,110033
2,784089,canceled,3/15/2018,OTHPCB5A7D8A1240398,12000.0,2,24000.00,100479699,Others,NaN,...,Easypay,3/15/2018,Gross,"24,000",2018,3,2018-3,Mar-18,FY18,95206
3,465260,complete,5/7/2017,KureshiC_141-kemei,1599.0,1,1599.00,100301652,Beauty & Grooming,\N,...,cod,5/7/2017,Net,"1,599",2017,5,2017-5,May-17,FY17,43645
4,846044,received,5/11/2018,BAGVIT5AC4A6DD68342,310.0,3,3853.32,100526623,Beauty & Grooming,NaN,...,Payaxis,5/11/2018,Valid,930,2018,5,2017-10,May-18,FY18,64430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,680616,canceled,11/24/2017,MEFNAR59C8CA4424D12,298.0,1,2470.00,100417366,Men's Fashion,\N,...,Easypay,11/24/2017,Gross,298,2017,11,2017-2,Nov-17,FY18,33717
9996,325420,canceled,11/25/2016,Enviro_Enviro 3 In 1 Juicer ENJ-301,3675.0,1,3307.50,100223641,Appliances,\N,...,jazzvoucher,11/25/2016,Gross,"3,675",2016,11,2016-9,Nov-16,FY17,8543
9997,649516,complete,11/20/2017,MATIGE59BA6458A8F79-1,1889.0,1,2338.00,100398958,Mobiles & Tablets,\N,...,cod,11/20/2017,Net,"1,889",2017,11,2017-11,Nov-17,FY18,72481
9998,391461,canceled,1/21/2017,cr_MUZAFTI IRANI (500GM),185.0,1,335.00,100262643,Soghaat,\N,...,Payaxis,1/21/2017,Gross,185,2017,1,2016-12,Jan-17,FY17,28952
9999,447254,order_refunded,4/15/2017,Aladdin_3D_enlarge_Screen,290.0,1,290.00,100293787,Mobiles & Tablets,\N,...,cod,4/15/2017,Valid,290,2017,4,2016-7,Apr-17,FY17,688

In [18]:
df["Month"].sum

<bound method Series.sum of 0        4
1        6
2        3
3        5
4        5
        ..
9995    11
9996    11
9997    11
9998     1
9999     4
Name: Month, Length: 10000, dtype: int64>

In [19]:
df["Month"].count

<bound method Series.count of 0        4
1        6
2        3
3        5
4        5
        ..
9995    11
9996    11
9997    11
9998     1
9999     4
Name: Month, Length: 10000, dtype: int64>

In [21]:
df["payment_method"].count

<bound method Series.count of 0           Easypay
1           Easypay
2           Easypay
3               cod
4           Payaxis
           ...
9995        Easypay
9996    jazzvoucher
9997            cod
9998        Payaxis
9999            cod
Name: payment_method, Length: 10000, dtype: object>

In [22]:
df["payment_method"].sum

<bound method Series.sum of 0           Easypay
1           Easypay
2           Easypay
3               cod
4           Payaxis
           ...
9995        Easypay
9996    jazzvoucher
9997            cod
9998        Payaxis
9999            cod
Name: payment_method, Length: 10000, dtype: object>

In [24]:
import streamlit as st

In [25]:
st.title("Data is here")

2025-04-30 20:06:01.799 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-30 20:06:02.347
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\User\AppData\Roaming\Python\Python313\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-04-30 20:06:02.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [27]:
import seaborn as sns

In [35]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,831156,order_refunded,4/25/2018,COMSAN5AA13CA206621,1188.0,1,1188.00,100516225,Computing,Cfsd80620,...,Easypay,4/25/2018,Valid,"1,188",2018,4,2017-12,Apr-18,FY18,83736
1,864213,canceled,6/1/2018,MATHUA5AF70B5D6ADF3,36000.0,1,36000.00,100537896,Mobiles & Tablets,NaN,...,Easypay,6/1/2018,Gross,"36,000",2018,6,2018-5,Jun-18,FY18,110033
2,784089,canceled,3/15/2018,OTHPCB5A7D8A1240398,12000.0,2,24000.00,100479699,Others,NaN,...,Easypay,3/15/2018,Gross,"24,000",2018,3,2018-3,Mar-18,FY18,95206
3,465260,complete,5/7/2017,KureshiC_141-kemei,1599.0,1,1599.00,100301652,Beauty & Grooming,\N,...,cod,5/7/2017,Net,"1,599",2017,5,2017-5,May-17,FY17,43645
4,846044,received,5/11/2018,BAGVIT5AC4A6DD68342,310.0,3,3853.32,100526623,Beauty & Grooming,NaN,...,Payaxis,5/11/2018,Valid,930,2018,5,2017-10,May-18,FY18,64430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,680616,canceled,11/24/2017,MEFNAR59C8CA4424D12,298.0,1,2470.00,100417366,Men's Fashion,\N,...,Easypay,11/24/2017,Gross,298,2017,11,2017-2,Nov-17,FY18,33717
9996,325420,canceled,11/25/2016,Enviro_Enviro 3 In 1 Juicer ENJ-301,3675.0,1,3307.50,100223641,Appliances,\N,...,jazzvoucher,11/25/2016,Gross,"3,675",2016,11,2016-9,Nov-16,FY17,8543
9997,649516,complete,11/20/2017,MATIGE59BA6458A8F79-1,1889.0,1,2338.00,100398958,Mobiles & Tablets,\N,...,cod,11/20/2017,Net,"1,889",2017,11,2017-11,Nov-17,FY18,72481
9998,391461,canceled,1/21/2017,cr_MUZAFTI IRANI (500GM),185.0,1,335.00,100262643,Soghaat,\N,...,Payaxis,1/21/2017,Gross,185,2017,1,2016-12,Jan-17,FY17,28952
9999,447254,order_refunded,4/15/2017,Aladdin_3D_enlarge_Screen,290.0,1,290.00,100293787,Mobiles & Tablets,\N,...,cod,4/15/2017,Valid,290,2017,4,2016-7,Apr-17,FY17,688

In [36]:
df.info

<bound method DataFrame.info of       item_id          status  created_at  \
0      831156  order_refunded   4/25/2018
1      864213        canceled    6/1/2018
2      784089        canceled   3/15/2018
3      465260        complete    5/7/2017
4      846044        received   5/11/2018
...       ...             ...         ...
9995   680616        canceled  11/24/2017
9996   325420        canceled  11/25/2016
9997   649516        complete  11/20/2017
9998   391461        canceled   1/21/2017
9999   447254  order_refunded   4/15/2017

                                      sku    price  qty_ordered  grand_total  \
0                     COMSAN5AA13CA206621   1188.0            1      1188.00
1                     MATHUA5AF70B5D6ADF3  36000.0            1     36000.00
2                     OTHPCB5A7D8A1240398  12000.0            2     24000.00
3                      KureshiC_141-kemei   1599.0            1      1599.00
4                     BAGVIT5AC4A6DD68342    310.0            3      3853.32
...                                   ...      ...          ...          ...
9995                  MEFNAR59C8CA4424D12    298.0            1      2470.00
9996  Enviro_Enviro 3 In 1 Juicer ENJ-301   3675.0            1      3307.50
9997                MATIGE59BA6458A8F79-1   1889.0            1      2338.00
9998             cr_MUZAFTI IRANI (500GM)    185.0            1       335.00
9999            Aladdin_3D_enlarge_Screen    290.0            1       290.00

     increment_id    category_name_1 sales_commission_code  ...  \
0       100516225          Computing             Cfsd80620  ...
1       100537896  Mobiles & Tablets                   NaN  ...
2       100479699             Others                   NaN  ...
3       100301652  Beauty & Grooming                    \N  ...
4       100526623  Beauty & Grooming                   NaN  ...
...           ...                ...                   ...  ...
9995    100417366      Men's Fashion                    \N  ...
9996    100223641         Appliances                    \N  ...
9997    100398958  Mobiles & Tablets                    \N  ...
9998    100262643            Soghaat                    \N  ...
9999    100293787  Mobiles & Tablets                    \N  ...

      payment_method Working Date BI Status     MV   Year  Month  \
0            Easypay    4/25/2018     Valid   1,188  2018      4
1            Easypay     6/1/2018     Gross  36,000  2018      6
2            Easypay    3/15/2018     Gross  24,000  2018      3
3                cod     5/7/2017       Net   1,599  2017      5
4            Payaxis    5/11/2018     Valid     930  2018      5
...              ...          ...       ...     ...   ...    ...
9995         Easypay   11/24/2017     Gross     298  2017     11
9996     jazzvoucher   11/25/2016     Gross   3,675  2016     11
9997             cod   11/20/2017       Net   1,889  2017     11
9998         Payaxis    1/21/2017     Gross     185  2017      1
9999             cod    4/15/2017     Valid     290  2017      4

      Customer Since     M-Y    FY Customer ID
0            2017-12  Apr-18  FY18       83736
1             2018-5  Jun-18  FY18      110033
2             2018-3  Mar-18  FY18       95206
3             2017-5  May-17  FY17       43645
4            2017-10  May-18  FY18       64430
...              ...     ...   ...         ...
9995          2017-2  Nov-17  FY18       33717
9996          2016-9  Nov-16  FY17        8543
9997         2017-11  Nov-17  FY18       72481
9998         2016-12  Jan-17  FY17       28952
9999          2016-7  Apr-17  FY17         688

[10000 rows x 21 columns]>